#! /bin/bash


# To stop fireall:
# sudo systemctl disable firewalld
# sudo systemctl stop    firewalld

MY_NAME=Brontonomicon
MY_ADDR=10.10.10.2
MY_PORT=9101

OTHER_ADDR=10.10.10.1
OTHER_PORT=9100

go run ./gotron.go ${MY_NAME} ${MY_ADDR} ${MY_PORT} ${OTHER_ADDR} ${OTHER_PORT}




